# Generated by Django 4.2.2 on 2023-07-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_project_description_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время выполнения'),
        ),
    ]
