# Generated by Django 4.2.2 on 2023-07-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_section_options_alter_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
