# Generated by Django 4.2.2 on 2023-11-11 11:02

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='project', chained_model_field='project', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='todo.section'),
        ),
    ]
