# Generated by Django 4.2.2 on 2023-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_node_text_note_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
