# Generated by Django 4.2.2 on 2023-09-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_slug',
        ),
    ]
