# Generated by Django 4.2.2 on 2023-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cards',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
