# Generated by Django 4.2.2 on 2023-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_folder_cards_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='cards',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Карточки'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название папки'),
        ),
    ]
